### ISSUE TITLE
MS InternetExplorer

### ISSUE THREAD

**Issue by VladimirS13** [Zer0CoolX/guacamole-customize-loginscreen-extension#2]
Extension works fine for me in Firefox , Opera etc. But MS IE 11 display wrong logo picture.
Solution is to add  tags:
`background-repeat: no-repeat;
background-size: cover;"
`
into the first section of login-override.css. 
Like this:
`
.login-ui .login-dialog .logo {
        background-image: url('app/ext/tempnamespace/images/logo-placeholder.png');
	width: 9em;
	-webkit-background-size: 9em auto;
	background-repeat: no-repeat;
	background-size: cover;
}
div.login-ui {
	background: #666;
	background-color: #666;
}
.login-ui .login-dialog {
	background-color: white;
}
`

**Comment by Zer0CoolX** [comment]
Thanks for sharing. Did you try clearing cache in IE prior?

I will do some more testing in IE 11 and see if I can reproduce the issue.

Can you provide some more details? Was this the default logo that would not display or one you replaced the default with? If you used your own image, what was the file type?

Thanks
