### ISSUE TITLE
How can I make small letters instead of capital?

### ISSUE THREAD

**Issue by joe-average-user** [Zer0CoolX/guacamole-customize-loginscreen-extension#4]
Hello,
the customize extension works great, but one question is left: how to use small letters instead of capitals? The text provided seems to get completely converted. Any hints?

**Comment by kbmorris** [comment]
@joe-average-user you will need to override the `text-transform: uppercase;` in the guacamole built-in CSS.
```
.login-ui .login-dialog .version .app-name {
    font-weight: bold;
    text-transform: uppercase;
    text-align: center;
    font-size: 1.25em;
}
```
Options are `text-transform: none|capitalize|uppercase|lowercase|initial|inherit;`
