### ISSUE TITLE
impossible to success xtension with latest 1.1 guacamole

### ISSUE THREAD

**Issue by vgaudin13** [Zer0CoolX/guacamole-customize-loginscreen-extension#5]
Hello,
Just trying to install custom login extension to an updated centos7.7.1908 and guacamole 1.1.0 in 
/var/lib/guacamole/extensions/branding.jar
then 
semanage fcontext -a -t tomcat_exec_t "/var/lib/guacamole/extensions/branding.jar"
restorecon -v "/var/lib/guacamole/extensions/branding.jar"
and restart guacd and/or reboot 

and still the original Template (with cache clear and test severals browsers)

is your extension still okay with 1.1 or I'am missing on step to install ?

**Comment by Zer0CoolX** [comment]
The extension should work with Guacamole 1.1.0. I will give it a quick test to be sure and let you know

**Comment by vgaudin13** [comment]
ok thks, I've tested many ways without success

**Comment by Zer0CoolX** [comment]
I can confirm it works on a fresh install of CentOS 7.7 using my install script for Guacamole 1.1.0 and this extension.

Permissions are rw/rw/r but that could likely be tightened up. Ownership/group is the user that ran the script (so just my user account, nothing special...could likely be root instead).

Context set by the script is:

```
semanage fcontext -a -t tomcat_exec_t "/var/lib/guacamole/extensions/branding.jar"
restorecon -v "/var/lib/guacamole/extensions/branding.jar"
```

Are you trying this with the branding.jar unchanged or have you tried modifying it first? If you changed it, I suggest trying with it as it is first to see if it displays, if so there may be an issue in the modifications you have made.

As you mention already clearing browser cache and trying other browsers I am not sure what other troubleshooting you can try.

Other then placing the extension in the proper place with the proper permissions and SEL context there should be no other steps to take (other than customizing the extension before hand to your liking).

I would run `tail -f /var/log/messages` when attempting to open the guacamole web GUI and see if the log picks up any error related to loading the page of extension. Not sure what else can be done beyond the above.

**Comment by vgaudin13** [comment]
firstly I try with my modified branding.jar and then come back to branding.jar from you.
I have not supposed the errors would be put in /var/log/messages.

so progress it is an error on selinux right

found messages:Mar  4 16:43:20 srv-guacamole setroubleshoot: failed to retrieve rpm info for /var/lib/guacamole/extensions/branding.jar
messages:Mar  4 16:43:20 srv-guacamole setroubleshoot: SELinux is preventing localhost-start from getattr access on the file /var/lib/guacamole/extensions/branding.jar. For complete SELinux messages run: sealert -l a0ce56bc-4637-4cf4-b513-f7fee0cb2d48
messages:Mar  4 16:43:20 srv-guacamole python: SELinux is preventing localhost-start from getattr access on the file /var/lib/guacamole/extensions/branding.jar.#012#012*****  Plugin restorecon (94.8 confidence) suggests   ************************#012#012If you want to fix the label. #012/var/lib/guacamole/extensions/branding.jar default label should be tomcat_exec_t.#012Then you can run restorecon. The access attempt may have been stopped due to insufficient permissions to access a parent directory in which case try to change the following command accordingly.#012Do#012#

**Comment by vgaudin13** [comment]
thks to point me to the correct way … after correcting SEL context, it's now running !

**Comment by Zer0CoolX** [comment]
Glad you have it working.
