### ISSUE TITLE
MySQL No Install Error

### ISSUE THREAD

**Issue by CHEFSneebly** [Zer0CoolX/guacamole-customize-loginscreen-extension#6]
Morning Zer0CoolX, first of all thanks for packaging this deployment has worked like a charm to get it up and running. We have grown our install, and wanted to attach a couple servers to a remote SQL server. However, when I run the script and choose not to install MySQL, it fails to restart the service as it is not found. Any recommendations to what I might need to change to overcome this issue?

**Comment by Zer0CoolX** [comment]
Sorry I am just seeing this now. I think you may have posted this issue in the wrong repo. If this is in regards to my install script for Guacamole please create a post there and follow the template for [HELP]. Fill it out as completely as possible. The more info you provide, the more detail and the clearer it is presented the better I may be able to help.

I will wait a few days to hear back or until you have posted in the other repo to close this issue.
