### ISSUE TITLE
Works great! Thank you. 

### ISSUE THREAD

**Issue by Search-and-Destroy** [Zer0CoolX/guacamole-customize-loginscreen-extension#7]
**UPDATE**

Figured it out myself actually. With the following css I was able to change every aspect (that i wanted) of the login page. Feel free to use it, just change the locations and names to yours. 

.login-ui .login-dialog .logo {
        background-image: url('app/ext/tempnamespace/images/XXXX.png');
        width: 9em;
        -webkit-background-size: 9em auto;
}
div.login-ui {
        background: url('app/ext/tempnamespace/images/XXXX.png');
        background-color: #000;
}
.login-ui .login-dialog {
        background-color: transparent;
}
.login-ui .login-dialog .version .version-number {
        display: none;
}
.login-ui .login-dialog .login.action_login {
        background-color: transparent;
}
.login-ui .login-dialog .login-fields input {
    display: block;
    border: 1px solid rgba(0, 0, 0, 0.25);
    -moz-border-radius: 0.2em;
    -webkit-border-radius: 0.2em;
    -khtml-border-radius: 0.2em;
    font-family: Carlito, FreeSans, Helvetica, Arial, sans-serif;
    font-size: 0.9em
    border-radius: 0.2em;
    width: 100%;
    margin: 0;
    margin-bottom: 0.5em;
    padding: 0.5em 0.75em;
    max-width: none;
}
.login-ui .login-dialog .buttons input[type="submit"] {
    width: 100%;
    margin: 0;
    background-color: transparent;
    opacity: 0.8;
}
.login-ui .login-fields .labeled-field .field-header {
  display: block;
  position: absolute;
  left: 0;
  right: 0;
  overflow: hidden;
  z-index: -1;
  margin: 0.5em;
  font-size: 0.9em;
  color: white;
  opacity: 0.8;
}
.login-ui .login-dialog .version .app-name {
    font-weight: bold;
    text-transform: uppercase;
    text-align: center;
    font-size: 1.00em;
    color: white;
    opacity: 0.8;
}

Thanks for this! Makes it easy enough to customize my guac setup. One question or request if you will. Is there a way to make the "login" button easily changeable as well?

**Comment by Zer0CoolX** [comment]
Glad it worked out. I would recommend reading: https://github.com/Zer0CoolX/guacamole-customize-loginscreen-extension#how-to-modify-the-extension-to-customize-the-apache-guacamole-login-screen. Specifically the part about using the dev tools and a generic login page to help identify how to make your desired changes.

Honestly I am not sure, but would assume, that the CSS can control the appearance of the login button at least to a degree. It depends how much of the login button is coded/hard coded in the HTML (or whatever programming language they use for elements of the page) and how much of it depends on CSS.

So your best bet is use a browsers dev tools, select the button and review its CSS code and make changes in the dev mode then carry over any changes to your extension that give the desired result. Doing anything beyond adjusting the CSS, JSON, etc related to the login page that the extension already does is beyond the scope I intended for it.
