### ISSUE TITLE
APP.NAME in Title and login page

### ISSUE THREAD

**Issue by Tacioandrade** [Zer0CoolX/guacamole-customize-loginscreen-extension#9]
Good night friend, I wanted to know the following, I downloaded the branding.jar file, edited the login image and downloaded the en.json file and put it like this:

{
    "NAME" : "English",
		
    "APP":{
	
	"NAME" : "MultiTI" 
	  }
}

However after restarting tomcat. instead of appearing the name MultiTI, only APP.NAME appears both in the title and below the logo.
I even created a pt.json and pt_BR.json file with the following content:

{
    "NAME" : "Português",
		
    "APP":{
	
	"NAME" : "MultiTI" 
	  }
}

However after restarting tomcat. instead of appearing the name MultiTI, only APP.NAME appears both in the title and below the logo.
I even created a pt.json and pt_BR.json file with the following content:

And yet AppAPP.NAME appears on the login screen, even when I remove branding.jar. Would you know what could be the problem?

PS: I'm from Brazil, so the language of my users' browsers is Brazilian Portuguese.

**Comment by Zer0CoolX** [comment]
I am sorry, I cannot help with modifying the extension. As per the readme, I recommend trying the following:

- Test your modifications using the browsers built in dev tools to test your desired changes.
- Start by using the extension unmodified to ensure it works before customizing it.

I am going to update the readme to make this more clear.

I have not personally tested this with systems other than US English.

**Comment by Tacioandrade** [comment]
I solved by directly editing the guacamole files:

sed -i 's/APP.NAME/MultiTI/g' /var/lib/tomcat9/webapps/guacamole/app/login/templates/login.html
sed -i 's/APP.NAME/MultiTI/g' /var/lib/tomcat9/webapps/guacamole/app/index/controllers/indexController.js
sed -i 's/APP.NAME/MultiTI/g' /var/lib/tomcat9/webapps/guacamole/app/index/config/indexRouteConfig.js
sed -i 's/APP.NAME/MultiTI/g' /var/lib/tomcat9/webapps/guacamole/guacamole.js
sed -i 's/APP.NAME/MultiTI/g' /var/lib/tomcat9/webapps/guacamole/guacamole.min.js
sed -i 's/APP.NAME/MultiTI/g' /var/lib/tomcat9/webapps/guacamole/generated/templates-main/templates.js
